
"project": "ResearchMAS"
models:
  "llm_model": "llama-3.3-70b-versatile"
  "bi_encoder": "BAAI/bge-small-en-v1.5"
  "cross_encoder": "BAAI/bge-reranker-base"

database:
  "checkpointer_path": "memory/checkpointer/checkpoints.db"
  "vectordb_path": "memory/vectordb"
